mt6895-common: Sync with tree
commit 7ffb3185e7e88616d6427f09297bf632f8eef041 (HEAD -> 17.0, origin/17.0)
Author: archcloudy <cloudguy9@proton.me>
Date:   Tue Aug 25 22:46:46 2026 +0700

    mt6895-common: Dolby cleanup

    Move dolby blobs to device tree

    Signed-off-by: archcloudy <cloudguy9@proton.me>

commit 259158927fc9098f12af58c86db9c948734061ad
Author: archcloudy <cloudguy9@proton.me>
Date:   Tue Aug 25 21:20:31 2026 +0700

    mt6895-common: patches: Fix ImsService emergency call crash

    Since A16, `includes(String)` in PackagesTagsList has been replaced by
    `containsPackage(String)`

    ImsLocationHandler still uses `includes(String)`, which causes
    NoSuchMethodError error from IMS when attempting to call emergency
    services.

    Patch ImsLocationHandler to use containsPackage(String) instead.

    [archcloudy]: Increase register count in ImsConfigManager also.

    (cherry-picked from d0ee2dc3c4e2a0c5284a49b9d30f439f60517ee7)
    Different commit message from original author
    This is the revised commit message.

    Change-Id: I53aeb9c8b6b58404f923d5953c486e2af01ca3b0
    Co-authored-by: Angaddeep Singh <angxddeep@gmail.com>
    Co-authored-by: codex <codex@users.noreply.github.com>
    Signed-off-by: archcloudy <cloudguy9@proton.me>

commit 91a89a6a8707417bd754dbfa9b59c505af9fd073
Author: archcloudy <cloudguy9@proton.me>
Date:   Tue Aug 25 13:52:57 2026 +0700

    fixup! mt6895-common: libsink-mtk add lineage-compat libaudioclient_shim.so

commit d5b02964a4244c707090be370483eb8961fac945
Author: Mashopy <eliasgheeraert@gmail.com>
Date:   Sat Aug 22 18:04:22 2026 +0200

    mt6895-common: Build wlan_assistant daemon from source

    Change-Id: If83a2faac76038bbec290bb626e0afc282fcd590

commit 94fc1c00249b303b46b791c8efe3876f461c357a
Author: Mashopy <eliasgheeraert@gmail.com>
Date:   Thu Aug 13 20:34:04 2026 +0200

    mt6895-common: Move back mediatek ims bootjars to system_ext

Signed-off-by: archcloudy <cloudguy9@proton.me>